import {useCallback,useEffect,useRef,useState} from 'react';import {CameraPanel} from './components/CameraPanel';import {CenterStage} from './components/CenterStage';import {GestureGuide} from './components/GestureGuide';import {RecipePanel} from './components/RecipePanel';import {TopBar} from './components/TopBar';import {VoiceBubble} from './components/VoiceBubble';import {BATTER_INGREDIENTS,BATTER_TOTAL,BOWL_STATES,MIXING_BOWL_STATES,isAddCommand,matchBatterIngredient} from './game/recipe';import type {GameFeedback} from './game/types';import {useGameAudio,type GameSound} from './hooks/useGameAudio';import {useHandTracking,type HandAction} from './hooks/useHandTracking';import {useSpeechRecognition} from './hooks/useSpeechRecognition';

export default function App(){
 const [added,setAdded]=useState<Set<string>>(new Set()),[selected,setSelected]=useState<string|null>(null),[mixProgress,setMixProgress]=useState(0),[makerScene,setMakerScene]=useState(false),[feedback,setFeedback]=useState<GameFeedback>(null),[loading,setLoading]=useState(true),[voiceEnabled,setVoiceEnabled]=useState(false);const videoRef=useRef<HTMLVideoElement>(null),feedbackTimer=useRef<number>(),selectedRef=useRef<string|null>(null),addedRef=useRef(added),mixRef=useRef(0);const {enabled:soundEnabled,toggle:toggleSound,play}=useGameAudio();selectedRef.current=selected;addedRef.current=added;mixRef.current=mixProgress;
 const showFeedback=useCallback((message:string,tone:'success'|'warning'|'info'='info')=>{window.clearTimeout(feedbackTimer.current);setFeedback({message,tone,id:Date.now()});feedbackTimer.current=window.setTimeout(()=>setFeedback(null),2200)},[]);
 const choose=useCallback((id:string)=>{const item=BATTER_INGREDIENTS.find(x=>x.id===id);if(!item||addedRef.current.has(id)){play('duplicate');showFeedback(`${item?.name||'Ingredient'} is already in the bowl`,'warning');return}setSelected(id);play('pickup');showFeedback(`${item.name} picked — ${item.instruction}`,'info')},[play,showFeedback]);
 const addSelected=useCallback((source:'mouse'|'voice'|'gesture',action?:HandAction)=>{const id=selectedRef.current,item=BATTER_INGREDIENTS.find(x=>x.id===id);if(!id||!item){showFeedback('Select an ingredient first','warning');play('error');return}if(action&&action!==item.gesture){showFeedback(`${item.name} needs: ${item.gesture}`,'warning');play('error');return}const sound:GameSound=item.id==='egg'?'crack':item.id==='baking-powder'?'sprinkle':item.id==='butter'?'add':'pour';play(sound);setAdded(current=>{const next=new Set(current);next.add(id);if(next.size===BATTER_TOTAL){window.setTimeout(()=>{play('complete');showFeedback('Batter ready — make circles to mix!','success')},600)}return next});setSelected(null);showFeedback(`${item.name} added to the bowl`,'success');if(source==='voice')play('mic')},[play,showFeedback]);
 const voiceCommand=useCallback((text:string)=>{const item=matchBatterIngredient(text);if(!item){play('error');showFeedback(`I couldn't match “${text}” to an ingredient`,'warning');return}choose(item.id);if(isAddCommand(text))window.setTimeout(()=>{selectedRef.current=item.id;addSelected('voice')},300)},[addSelected,choose,play,showFeedback]);
 const speech=useSpeechRecognition(voiceCommand);
 const handAction=useCallback((action:HandAction,x:number,y:number)=>{if(action==='Pinch'){const target=document.elementFromPoint(x*window.innerWidth,y*window.innerHeight)?.closest<HTMLElement>('[data-ingredient]');if(target?.dataset.ingredient)choose(target.dataset.ingredient);else showFeedback('Point at an ingredient, then pinch','info');return}if(action==='Circle'&&addedRef.current.size===BATTER_TOTAL){setMixProgress(value=>{const next=Math.min(100,value+25);if(next===100)showFeedback('Batter is smooth — first step complete!','success');return next});return}addSelected('gesture',action)},[addSelected,choose,showFeedback]);
 const tracking=useHandTracking(videoRef,handAction);
 useEffect(()=>{const assets=['/assets/waffle/background-kitchen.png','/assets/waffle/background-batter-mixing.png','/assets/waffle/background-waffle-maker.png','/assets/waffle/waffle-maker.png',...BATTER_INGREDIENTS.map(item=>item.asset),...BOWL_STATES,...MIXING_BOWL_STATES];let alive=true;Promise.all(assets.map(src=>new Promise<void>(resolve=>{const image=new Image();image.onload=image.onerror=()=>resolve();image.src=src}))).then(()=>alive&&setLoading(false));const fallback=window.setTimeout(()=>setLoading(false),2200);return()=>{alive=false;window.clearTimeout(fallback)}},[]);
 useEffect(()=>{if(tracking.status==='tracking')play('tracking');if(tracking.status==='lost')showFeedback('Move your hand into view','warning')},[tracking.status,play,showFeedback]);useEffect(()=>()=>window.clearTimeout(feedbackTimer.current),[]);useEffect(()=>{if(mixProgress!==100)return;const timer=window.setTimeout(()=>setMakerScene(true),1400);return()=>window.clearTimeout(timer)},[mixProgress]);
 const reset=()=>{setAdded(new Set());setSelected(null);setMixProgress(0);setMakerScene(false);setFeedback(null)};const toggleMic=()=>{if(speech.status==='listening')speech.stop();else{setVoiceEnabled(true);speech.start();play('mic')}};
 const mixing=added.size===BATTER_TOTAL;
 return <main className={`game-shell batter-only ${mixing&&!makerScene?'mixing-phase':''} ${makerScene?'maker-phase':''}`}><img key={makerScene?'maker':mixing?'mixing':'kitchen'} className="kitchen-background scene-background" src={makerScene?'/assets/waffle/background-waffle-maker.png':mixing?'/assets/waffle/background-batter-mixing.png':'/assets/waffle/background-kitchen.png'} alt={makerScene?'Top-down illustrated waffle-maker counter':mixing?'Illustrated wooden batter mixing table':'Warm illustrated waffle kitchen with an open wooden worktable'}/><div className="game-vignette"/><TopBar sound={soundEnabled} onSound={toggleSound} onReset={reset}/>{makerScene&&<section className="waffle-maker-stage"><img src="/assets/waffle/waffle-maker.png" alt="Waffle maker machine"/></section>}{!makerScene&&<>{!mixing&&<RecipePanel added={added} selected={selected} onChoose={choose}/>}<CameraPanel videoRef={videoRef} status={tracking.status} gesture={tracking.gesture} mixing={mixing} onEnable={()=>{play('click');tracking.start()}} onContinue={()=>showFeedback('Mouse controls are ready','info')}/><GestureGuide selected={selected} ready={mixing} detected={tracking.gesture}/><CenterStage added={added} selected={selected} mixProgress={mixProgress} onChoose={choose} onDropIngredient={id=>{selectedRef.current=id;setSelected(id);window.setTimeout(()=>addSelected('mouse'),0)}}/><VoiceBubble enabled={voiceEnabled} listening={speech.status==='listening'||speech.status==='requesting'} transcript={speech.transcript} message={speech.errorMessage||'Voice control ready'} onToggle={toggleMic}/></>}{tracking.cursor&&!makerScene&&<div className="hand-cursor" style={{left:`${tracking.cursor.x*100}%`,top:`${tracking.cursor.y*100}%`}}><span/></div>}{feedback&&!makerScene&&<div key={feedback.id} className={`game-toast ${feedback.tone}`}><b>{feedback.tone==='success'?'Success':feedback.tone==='warning'?'Try again':'Gesture'}</b><span>{feedback.message}</span></div>}{loading&&<div className="start-layer"><section className="start-card"><p>Waffle Kitchen</p><h1>Preparing batter station…</h1><span>Setting the bowl and ingredients on the table.</span></section></div>}</main>
}
